# SPDX-License-Identifier: MIT
# Inputs:
#   __systemd_user_name
# Outputs:
#   __systemd_user_info updated with getent info from user
---
- name: Get user information
  getent:
    database: passwd
    key: "{{ __systemd_user_name }}"
    fail_key: true
  when: "'getent_passwd' not in ansible_facts or
    __systemd_user_name not in ansible_facts['getent_passwd']"

- name: Update systemd user info with new user info
  when: __systemd_user_name not in __systemd_user_info
  set_fact:
    __systemd_user_info: "{{ __systemd_user_info | combine({__systemd_user_name: user_dict}) }}"
  vars:
    getent: "{{ ansible_facts['getent_passwd'][__systemd_user_name] }}"
    user_dict:
      xdg_dir: /run/user/{{ getent[1] }}
      units_dir: "{{ __admin_units_dir if __systemd_user_name == 'root'
        else getent[4] ~ '/' ~ __user_units_dir }}"
      group: "{{ getent[2] }}"
